### ISSUE TITLE
Graphical artifacts with Webrender on HiDPI displays.

### ISSUE THREAD

**Issue by Bira** [emacs-ng/emacs-ng#227] opened 2021-04-27 13:43 UTC
![font-issue](https://user-images.githubusercontent.com/2083/116251203-d64e4300-a744-11eb-9d38-2d5d629a237e.png)

**Describe the bug**
When emacs-ng is built with webrender, it displays weird graphical artifacts when run in a HiDPI display. Scrolling its display makes "patches" of zoomed-in text appear over the buffer display, and they "tear" as you move the cursor over their area. 

**To Reproduce**
Build emacs-ng `--with-webrender`, and run the resulting binary using `src/emacs -q`, on a HiDPI display. Open a file that's more than a screen long (`rust_src/src/webrender_backend/term.rs` works for this) and scroll up and down through it. This happens both with mouse-wheel scrolling and with keyboard scrolling (arrows or page-up/page-down commands). 

I'm using a variant of the build script that comes with the repository to build my local emacs-ng, but I think the `--with-webrender` config option is the key here.

```shell
#!/bin/bash
./autogen.sh

./configure CFLAGS="-Wl,-rpath,shared -Wl,--disable-new-dtags" \
            --with-json --with-modules --with-harfbuzz --with-compress-install \
            --with-threads --with-included-regex --with-zlib --with-cairo --with-libsystemd \
            --with-rsvg --with-native-compilation --with-webrender --without-javascript \
            --without-sound --without-imagemagick --without-makeinfo --without-gpm --without-dbus \
            --without-pop --without-toolkit-scroll-bars --without-mailutils --without-gsettings \
            --with-all

make NATIVE_FULL_AOT=1 PATH=$PATH:$HOME/.cargo/bin -j$(($(nproc) * 2))

```

**Expected behavior**
The screen should display without graphical artifacts. 

**OS**
Ubuntu 20.04 with kernel 5.8.0-50-generic .

**Comment by ReggieMarr** [comment] 2021-05-03 00:21
I'm having the same issue when built --with-webrender. I had built from source but then also downloaded the [package from aur](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=emacs-ng-git).
Is this suspected to be related to font issues ?

**Comment by harryfei** [comment] 2021-05-03 09:00
I don't know why those things occurs. But I think it's not related to font configuration.

**Comment by harryfei** [comment] 2021-05-03 12:29
@Bira Can you guys try this branch which I try to fix this HiDPI issue.
https://github.com/harryfei/emacs-ng/commit/82a1c4b90318eb318554954fa9f472b951b4dba8

**Comment by Bira** [comment] 2021-05-03 12:50
This seems to have done the trick! With the changes from that branch applied on top of master, I no longer see the artifacts when scrolling around on that same file.

**Comment by ReggieMarr** [comment] 2021-05-03 13:40
@harryfei that didn't seem to work for me. I don't see scrolling artifacts anymore but now I see just a blank white screen.

That being said there appears to be issues with my config (odd since there werent before building this branch). I'll retry once I fix those

**Comment by harryfei** [comment] 2021-05-03 13:57
Ok, thanks you both. I think the patch does work for scrolling artifacts bug.

**Comment by ReggieMarr** [comment] 2021-05-03 14:04
@harryfei the config issue in question might be related to this branch. I now get an error related to `make-closure` function being void. This doesn't seem to be the case when built off master/or the source emacs-ng. and `make-closure` is defined in source (although doesn't seem to be related to the changes in your fork)
What are you using to build ? I'm using the following :
```
./autogen.sh
./configure --prefix=/usr \
            --sysconfdir=/etc \
            --libexecdir=/usr/lib \
            --localstatedir=/var \
            --with-x-toolkit=gtk3 \
            --with-xft \
            --with-wide-int \
            --with-modules \
            --with-cairo \
            --with-harfbuzz \
            --with-nativecomp \
            --with-webrender
 make -j8
```

**Comment by harryfei** [comment] 2021-05-03 14:13
@ReggieMarr 
Personally I just use this in my test builds.
```bash
./configure --with-native-compilation --with-webrender
```
There are few issues in your arguments. I don't know whether them relates to your display issue.
* `--with-nativecomp` option has been changed into `--with-native-compilation`
* `--with-x-toolkit`, `--with-xft`, `--with-cairo` and `--with-harfbuzz` are not needed when using `--with-webrender` at the same time.

**Comment by ReggieMarr** [comment] 2021-05-03 15:23
@harryfei it looks like I had needed to recompile the bytecode (I'm using doom) I rebuilt and I'm seeing the same issue as before now

**Comment by harryfei** [comment] 2021-05-03 15:36
Ok, got it. Yours seems an another bug (which I don't know how to fix currently).

> I don't know why those things occurs. But I think it's not related to font configuration.
> The webrender's render code locates in
> 
>     * https://github.com/emacs-ng/emacs-ng/blob/master/rust_src/src/webrender_backend/term.rs
> 
>     * https://github.com/emacs-ng/emacs-ng/blob/master/rust_src/src/webrender_backend/draw_canvas.rs
>       There must be some bugs there.
If you want to, try to debug those code to collect more information. :)

**Comment by Delanii** [comment] 2021-05-04 21:25
Having the same scrolling issue as @ReggieMarr I built emacs with webrender support, just now. I am using Doom Emacs too. I am having other issues with window display that will report and am willing to test or help resolve, but in the meantime, generally, if I have to use emacs and revert to standard emacs, how can I use emacs-ng parallel to standard emacs?
It seems that might be more complicated when doom emacs comes on board because when I tryed to run both standard and emacs-ng I got pretty unfriendly errors from emacs-ng ...

**Comment by Bira** [comment] 2021-05-05 01:33
For my basic tests above I built using `configure` and `make` without installing emacs-ng system wide, then ran it using `src/emacs -q` to load without any external configurations (I use Prelude for my local emacs install).

I tried running it without the `-q` option and it seemed to load most of prelude just fine. I got a lot of compilation warnings for the prelude elisp files, and a couple of errors after I updated some of the ELPA packages Prelude pulled in (I think the errors were on doom-themes in fact). 

When switching back to my default emacs, I found I had to delete the `.elc` files from my `~/.emacs.d` directory before it would load correctly.

**Comment by ReggieMarr** [comment] 2021-05-05 01:42
@Delanii I also find it difficult to run two parallel systems. The big issue is that whatever emacs your running should be the one called when running `doom build` (and this should be run each time after you switch)

**Comment by Delanii** [comment] 2021-05-05 06:06
@Bira @ReggieMarr Thank you for your adivces guys! I test running emacs-ng with `-q` later today, but, @ReggieMarr , supposedly, if I have emacs-ng in  `~/emacs-ng/src/emacs` how should I call `doom build` exactly? I wouldnt mind rebuilding whole distribution in comparison to building whole emacs (which I have went through 4 times yesteday :D)
I am affraid that this might be (somehow) doom emacs related issue, since we have same problem using same distribution ...

**Comment by ReggieMarr** [comment] 2021-05-05 13:26
@Delanii I'm not sure exactly. This is a problem I'm trying to solve myself but I know if you look at the impl of the `doom [cmd]` executable you can see that it's calling emacs from the `PATH`. One way I could imagine going about it is making sure neither standard emacs or emacs-ng are installed to a spot in the typical `PATH` and instead add them on demand and then run `doom build` to recompile the distro's packages appropriately.

**Comment by harryfei** [comment] 2021-06-04 16:19
@ReggieMarr Do you still have the scroll artifacts issue? Could we close this issue?

**Comment by ReggieMarr** [comment] 2021-06-04 19:04
@harryfei yes I still have this issue on my lenovo laptop but it works on my work laptop. I've been pretty busy the last couple weeks but I'll try and update this with some details and further testing

**Comment by ReggieMarr** [comment] 2021-06-05 16:01
@harryfei so I have two systems using the same kernel (5.10) and distro (manjaro xfce) very similar setups beyond that as well. What sorts of things should I compare ? Could this be an issue with my graphics card driver ?

**Comment by harryfei** [comment] 2021-06-05 16:17
@ReggieMarr Yeah, check the graphics card driver (opengl library).

**Comment by ReggieMarr** [comment] 2021-06-05 17:07
working laptop has the following:

```
↑4% ❯ glxinfo | rg -i opengl
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 630 (KBL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 21.0.3
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.0.3
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.0.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

```

**Comment by harryfei** [comment] 2021-06-05 17:12
Thanks. The non-working one is mesa software implementation.
I will debug on this environment if I get time.

**Comment by ReggieMarr** [comment] 2021-06-05 17:52
Occasionally when I startup I get a crash with the following error. I have a feeling it has something to do with this.
```
❯ RUST_BACKTRACE=1RUST_BACKTRACE=full ./src/emacs                                                                                                                                                                                              
[xcb] Unknown sequence number while processing queue                                                                                                                                                                                           
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called                                                                                                                                                         
[xcb] Aborting, sorry about that.                                                                                                                                                                                                              
emacs: xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.                                                                                                                                                       
Fatal error 6: Aborted                                                                                                                                                                                                                         
Backtrace:                                                                                                                                                                                                                                     
./src/emacs(+0x3dc465)[0x563144edc465]                                                                                                                                                                                                         
./src/emacs(+0x3dc539)[0x563144edc539]                                                                                                                                                                                                         
/usr/lib/libpthread.so.0(+0x13960)[0x7f9b9417e960]                                                                                                                                                                                             
/usr/lib/libc.so.6(gsignal+0x145)[0x7f9b91fa9ef5]                                                                                                                                                                                              
/usr/lib/libc.so.6(abort+0x116)[0x7f9b91f93862]                                                                                                                                                                                                
/usr/lib/libc.so.6(+0x26747)[0x7f9b91f93747]                                                                                                                                                                                                   
/usr/lib/libc.so.6(+0x35646)[0x7f9b91fa2646]                                                                                                                                                                                                   
/usr/lib/libX11.so.6(+0x40d91)[0x7f9b8d52fd91]                                                                                                                                                                                                 
/usr/lib/libX11.so.6(+0x40e3e)[0x7f9b8d52fe3e]                                                                                                                                                                                                 
/usr/lib/libX11.so.6(_XEventsQueued+0x82)[0x7f9b8d5301f2]                                                                                                                                                                                      
/usr/lib/libX11.so.6(_XGetRequest+0x56)[0x7f9b8d5331f6]                                                                                                                                                                                        
/usr/lib/libX11.so.6(XCreateGC+0x110)[0x7f9b8d50e8d0]                                                                                                                                                                                          
/usr/lib/libGLX_mesa.so.0(+0x32466)[0x7f9b8d2da466]                                                                                                                                                                                            
/usr/lib/libGLX_mesa.so.0(+0x3e207)[0x7f9b8d2e6207]                                                                                                                                                                                            
/usr/lib/libGLX_mesa.so.0(+0x3e33c)[0x7f9b8d2e633c]                                                                                                                                                                                            
/usr/lib/libGLX_mesa.so.0(+0x36bbd)[0x7f9b8d2debbd]                                                                                                                                                                                            
/usr/lib/libGLX.so.0(+0x13e03)[0x7f9b8d335e03]                                                                                                                                                                                                 
/usr/lib/libGLX.so.0(+0x16851)[0x7f9b8d338851]                                                                                                                                                                                                 
/usr/lib/libGLX.so.0(+0x1985d)[0x7f9b8d33b85d]                                                                                                                                                                                                 
./src/emacs(+0xc144e5)[0x5631457144e5]                                                                                                                                                                                                         
./src/emacs(+0x10dba16)[0x563145bdba16]                                                                                                                                                                                                        
./src/emacs(+0x10aa1b9)[0x563145baa1b9]                                                                                                                                                                                                        
./src/emacs(+0x10a9698)[0x563145ba9698]                                                                                                                                                                                                        
./src/emacs(+0x10a9528)[0x563145ba9528]                                                                                                                                                                                                        
./src/emacs(+0x10a9509)[0x563145ba9509]                                                                                                                                                                                                        
./src/emacs(+0x10a94ea)[0x563145ba94ea]                                                                                                                                                                                                        
./src/emacs(+0x10f6181)[0x563145bf6181]                                                                                                                                                                                                        
./src/emacs(+0x10f6162)[0x563145bf6162]                                                                                                                                                                                                        
./src/emacs(+0x10f6143)[0x563145bf6143]                                                                                                                                                                                                        
./src/emacs(+0x10f6124)[0x563145bf6124]                                                                                                                                                                                                        
./src/emacs(+0x10f60c3)[0x563145bf60c3]                                                                                                                                                                                                        
./src/emacs(+0xedd9c5)[0x5631459dd9c5]                                                                                                                                                                                                         
/usr/lib/libpthread.so.0(+0x9299)[0x7f9b94174299]                                                                                                                                                                                              
/usr/lib/libc.so.6(clone+0x43)[0x7f9b9206c053]                                                                                                                                                                                                 
[1]    7740 abort (core dumped)  RUST_BACKTRACE=1RUST_BACKTRACE=full ./src/emacs   
```

**Comment by ReggieMarr** [comment] 2021-06-05 18:22
Ok I think I'm getting somewhere now.
working laptop:
```
↑4% ❯ sudo inxi -G                                  
[sudo] password for reggiemarr: 
Graphics:  Device-1: Intel HD Graphics 630 driver: i915 v: kernel 
           Device-2: NVIDIA GM206GLM [Quadro M2200 Mobile] driver: nvidia v: 460.73.01 
           Display: server: X.Org 1.20.11 driver: loaded: modesetting,nvidia unloaded: intel,nouveau 
           resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa Intel HD Graphics 630 (KBL GT2) v: 4.6 Mesa 21.0.3 
```

**Comment by harryfei** [comment] 2021-06-06 13:01
>  Display: server: X.Org 1.20.11 driver: loaded: nvidia note: n/a (using device driver) failed: nvidia 
I think it's the root cause. Can you fix this and see what will happen?

**Comment by ReggieMarr** [comment] 2021-06-08 02:43
@harryfei I think you were right. After fiddling with reinstalling the graphics drivers, adding nvidia as a module to my initramfs and having my xorg config regenerated one of those things fixed my graphics issues and with it this issue

**Comment by harryfei** [comment] 2021-06-09 16:00
Ok, close this now.

**Closed by harryfei** 2021-06-09 16:00 UTC
Labels: bug, webrender
