### ISSUE TITLE
Font "Monospace" is not defined from feature of webrender.

### ISSUE THREAD

**Issue by GTrunSec** [emacs-ng/emacs-ng#218] opened 2021-04-14 21:08 UTC
When compiled with `--with-webrender`, Emacs tries a default font named "monospace-12".

I found similar  information here: https://lists.gnu.org/r/emacs-devel/2008-10/msg00696.html

compiling configFlags
```
configure flags: --prefix=/nix/store/33a8xgpcljisyqizgvp0ai5x57yddsw6-emacsNg-b2b5f92 --disable-build-details --with-modu
les --with-x-toolkit=gtk3 --with-cairo --with-native-compilation --with-imagemagick --with-json --with-threads --with-inc
luded-regex --with-harfbuzz --with-compress-install --with-zlib --with-dumping=pdumper --with-webrender --with-dbus
```
I think, the flag of `--with-x-toolkit=gtk3 ` does not need in webrender anymore.
- modified 
```
configure flags: --prefix=/nix/store/iv52bqgiihdw4cwyh6yclzzb9s3p8h2r-emacsNg-b2b5f92 --disable-build-details --with-modu
les --with-cairo --with-native-compilation --with-imagemagick --with-json --with-threads --with-included-regex --with-har
fbuzz --with-compress-install --with-zlib --with-dumping=pdumper --with-webrender --with-dbus
```
- LIB_PATH check

```
patchelf --print-rpath ./result/bin/.emacs-28.0.50-wrapped 
/nix/store/6x61c9dv420kvbwrz71l3gc5z7ib3qs1-dbus-1.12.20-lib/lib:/nix/store/1q7a4dq6fn4r0ggz6nynmbrlg8r6876w-libxml2-2.9.10/lib:/nix/store/xbxdy7pxgnplbg1ia1qgsyl9w1sxls2i-freetype-2.10.4/lib:/nix/store/ninay60p6hnd3cb7shn6xmd0spx0vs61-fontconfig-2.13.92-lib/lib:/nix/store/nbd5zwk69cizbq5h6dvw8p5cnr68swkc-gnutls-3.7.1/lib:/nix/store/nxiq4wnjh1bd4mahah164rkghfm1pdxx-lcms2-2.12/lib:/nix/store/ixpwj1cxl4rp2qbyn0s2h4k5zj731q7c-systemd-247.6/lib:/nix/store/ywzwrg8qmz26ykln8rj2ixnxpbp5sybs-jansson-2.13.1/lib:/nix/store/hdpihl2yn8cpdqmc9sysbh3fvwsxchky-ncurses-6.2/lib:/nix/store/8r5z8wlvz8visx2zm38hcqym07w9mpdd-zlib-1.2.11/lib:/nix/store/ak9n4w3nsnvn5gxqyi3dhc342yk9ia06-gmp-6.2.1/lib:/nix/store/rqa3ka051p5x6w6spr6kaglmqjs52n2x-libselinux-3.0/lib:/nix/store/ypfymbcixk4gzwpp9907v7db6q72in6i-libgccjit-10.2.0/lib:/nix/store/1jn6apz0fa9h9x7rl3v6vwiymwnjznwv-glibc-2.32-40/lib:/nix/store/nwfn0qi7lk2fskjh7x0hr1ak7slvgr6x-libX11-1.7.0/lib:/nix/store/vny5ghyhmm84gvx6j5862zmaa5n424z5-glu-9.0.1/lib:/nix/store/v3xi47p44wfdgc06hw9i90nqdja7d2xn-libGL-1.3.2/lib:/nix/store/96182q4x410s581d3cn825xcgzpj0m4i-libXpm-3.5.13/lib:/nix/store/vbd3xl7cwlrhf8h9sgxj76cwyh8nzhdf-libXext-1.3.4/lib:/nix/store/g2sbnn10fiw5011ylpxwacb6acpyj9jm-libXxf86vm-1.1.4/lib:/nix/store/1w1mzpgr015jxdzgj5365yqspd2jrc8h-alsa-lib-1.2.4/lib:/nix/store/rshs1xpkfs493qa0bzz64vlcnh6bcm4z-libxkbcommon-1.1.0/lib:/nix/store/7fnq0qvpvgj04gdf2l6hmgpz8dk72r1z-wayland-1.19.0/lib
```

TEST platform:
OS: NixOS
Build: Nix-build

**Comment by GTrunSec** [comment] 2021-04-14 23:25
test with ubuntu and nix on Vbox
![image](https://user-images.githubusercontent.com/21156405/114792832-ed9d3180-9d3d-11eb-9e22-5accc39d3076.png)

**Comment by black7375** [comment] 2021-04-15 02:19
It has also happened in manjaro before.

**Comment by Bira** [comment] 2021-04-15 16:49
This also happened on Ubuntu 20.04 for me, when I built emags-ng on my environment (no containers).

**Comment by harryfei** [comment] 2021-04-18 07:14
https://github.com/emacs-ng/emacs-ng/blob/fff21fcc5c584762d6b72e0cfa6864a2416d384e/rust_src/src/wrterm.rs#L257-L266

The webrender backend use `Monospace` as default font.
We can change logic here. we can use the system defined font as default font.

**Comment by GTrunSec** [comment] 2021-04-18 07:26
> We can change logic here. we can use the system defined font as default font.
Sounds good.
I think the emacs needs to fix the font setting problem such as emacs -fn `` and conf in Xresources, which I have mentioned [before](https://lists.gnu.org/r/emacs-devel/2008-10/msg00696.html).

Just make sure the users can be setting the different font set by override flags or envrs.

**Comment by black7375** [comment] 2021-04-18 12:56
> Oops, the policy of detection font automatically would be a good way.

I know [servo/font-kit](https://github.com/servo/font-kit) is possible.

**Comment by harryfei** [comment] 2021-04-26 15:02
I find the root cause. Fixed in #226 .

**Comment by GTrunSec** [comment] 2021-04-27 02:08
I got too many operational errors when running emacs with webrender under high DPI.

**Comment by GTrunSec** [comment] 2021-04-27 03:53
https://user-images.githubusercontent.com/21156405/116182642-7f5b5600-a6d1-11eb-9f9d-3b0b7a01f1ef.mp4

**Closed** 2021-04-27 06:40 UTC
Labels: webrender

**Comment by harryfei** [comment] 2021-04-27 06:42
Could you create a new issue to track the High DPI bugs?😀

**Comment by Bira** [comment] 2021-04-27 13:45
I just created one, it's at https://github.com/emacs-ng/emacs-ng/issues/227 .

**Comment by apo-llonx** [comment] 2021-07-29 16:22
I still get this issue on NixOS configured using pure flakes, even when trying to start it with -fn flag using any installed font. What is the backend for locating fonts for webrender? I tried looking through sources with my absolute zero Rust experience, and it seemed like it gets fonts using imported C constructs from standard emacs code. So if that's the case wouldn't it make sense to use standard emacs backends like harfbuzz, cairo, freetype, or fontconfig?

**Comment by harryfei** [comment] 2021-07-29 16:30
@apo-llonx 
https://github.com/emacs-ng/emacs-ng/blob/master/rust_src/crates/webrender/src/font.rs
https://github.com/emacs-ng/emacs-ng/blob/master/rust_src/crates/webrender/src/font_db.rs
Those are Webrender's font code.
