### ISSUE TITLE
build failed due to without linking expat lib

### ISSUE THREAD

**Issue by edenzhong7** [emacs-ng/emacs-ng#219] opened 2021-04-17 07:27 UTC
if i add `-lexpat` to the end, it's ok

```
/usr/bin/gcc-9 -o temacs.tmp \
  -Demacs  -I. -I. -I../lib -I../lib         -isystem /usr/include/libxml2          -isystem /usr/local/include -isystem /usr/include/freetype2    -MMD -MF deps/.d -MP   -isystem /usr/include/p11-kit-1    -pthread -DEMACS_EXTERN_INLINE -fno-common -Wall -Wdate-time -Wdisabled-optimization -Wdouble-promotion -Wduplicated-cond -Wextra -Wformat-signedness -Winit-self -Winvalid-pch -Wlogical-op -Wmissing-declarations -Wmissing-include-dirs -Wmissing-prototypes -Wnested-externs -Wnull-dereference -Wold-style-definition -Wopenmp-simd -Wpacked -Wpointer-arith -Wstrict-prototypes -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wsuggest-final-methods -Wsuggest-final-types -Wtrampolines -Wuninitialized -Wunknown-pragmas -Wunused-macros -Wvariadic-macros -Wvector-operation-performance -Wwrite-strings -Warray-bounds=2 -Wattribute-alias=2 -Wformat=2 -Wformat-truncation=2 -Wimplicit-fallthrough=5 -Wshift-overflow=2 -Wvla-larger-than=4031 -Wredundant-decls -Wno-missing-field-initializers -Wno-override-init -Wno-sign-compare -Wno-type-limits -Wno-unused-parameter -Wno-format-nonliteral -Wl,-rpath,shared -Wl,--disable-new-dtags   -L.././rust_src/target/release \
    dispnew.o frame.o scroll.o xdisp.o menu.o  window.o charset.o coding.o category.o ccl.o character.o chartab.o bidi.o cm.o term.o terminal.o xfaces.o    emacs.o keyboard.o macros.o keymap.o sysdep.o bignum.o buffer.o filelock.o insdel.o marker.o minibuf.o fileio.o dired.o cmds.o casetab.o casefiddle.o indent.o search.o regex-emacs.o undo.o alloc.o pdumper.o data.o doc.o editfns.o callint.o eval.o floatfns.o fns.o font.o print.o lread.o emacs-module.o syntax.o  bytecode.o comp.o dynlib.o process.o gnutls.o callproc.o region-cache.o sound.o timefns.o atimer.o doprnt.o intervals.o textprop.o composite.o xml.o lcms.o inotify.o  profiler.o decompress.o thread.o systhread.o        fontset.o fringe.o image.o  json.o  -lemacsng terminfo.o lastfile.o      ../lib/libgnu.a                -lrt       -lxml2    -ltinfo     -lfontconfig -lfreetype    -lgnutls -lpthread -lanl   -lm -lz -ldl  -ljansson -lgmp -lgccjit -ldl -ldl -lm -lrt -lstdc++
.././rust_src/target/release/libemacsng.a(fcxml.o): In function `FcConfigMessage':
fcxml.c:(.text+0x6f9): undefined reference to `XML_GetCurrentLineNumber'
fcxml.c:(.text+0x743): undefined reference to `XML_GetCurrentLineNumber'
.././rust_src/target/release/libemacsng.a(fcxml.o): In function `IA__FcConfigParseAndLoad':
fcxml.c:(.text+0x5222): undefined reference to `XML_ParserCreate'
fcxml.c:(.text+0x528b): undefined reference to `XML_SetUserData'
fcxml.c:(.text+0x52a8): undefined reference to `XML_SetDoctypeDeclHandler'
fcxml.c:(.text+0x52c5): undefined reference to `XML_SetElementHandler'
fcxml.c:(.text+0x52db): undefined reference to `XML_SetCharacterDataHandler'
fcxml.c:(.text+0x52ef): undefined reference to `XML_GetBuffer'
fcxml.c:(.text+0x5396): undefined reference to `XML_ParseBuffer'
fcxml.c:(.text+0x53a9): undefined reference to `XML_GetErrorCode'
fcxml.c:(.text+0x53b0): undefined reference to `XML_ErrorString'
fcxml.c:(.text+0x5412): undefined reference to `XML_ParserFree'
collect2: error: ld returned 1 exit status
Makefile:740: recipe for target 'temacs' failed

```

**Comment by DavidDeSimone** [comment] 2021-04-17 09:38
Thank you for this report. What OS you are operating on, and what were the options you passed to `configure`?

**Comment by edenzhong7** [comment] 2021-04-17 13:06
> Thank you for this report. What OS you are operating on, and what were the options you passed to `configure`?

thx for your replying, I built it on debian 9 with gcc-9, and when i run emacs in daemon mode, it will crash everytime after using emacsclient  a few minutes

```
./configure CFLAGS="-Wl,-rpath,shared -Wl,--disable-new-dtags" \
            --with-json --with-modules --with-harfbuzz --with-compress-install \
            --with-threads --with-included-regex --with-zlib --with-cairo --with-libsystemd \
            --with-rsvg --with-native-compilation --with-webrender\
            --without-sound --without-imagemagick --without-makeinfo --without-gpm --without-dbus \
            --without-pop --without-toolkit-scroll-bars --without-mailutils --without-gsettings \
            --with-all
```

**Comment by DavidDeSimone** [comment] 2021-04-17 18:16
Another team member might be able to try to reproduce this before I do, otherwise I’ll have time to look at this tomorrow. 

Do you have a stack trace for the case where the program crashes? And does this reproduce if you build without webrender?

**Comment by edenzhong7** [comment] 2021-04-18 02:46
expat problem may be due to I run configure command seperately instead of using build_emacs_ng.sh, i tried `./build_emacs_ng.sh 28.0.50` and `./build_emacs_ng.sh 28.0.50 --with-webrender` both are ok.

**Comment by edenzhong7** [comment] 2021-04-18 02:58
bad news....crash again when compiling vterm, run emacs directly, no in daemon mode
```
Fatal error 11: Segmentation fault
Backtrace:
emacs[0x555b0d]
emacs[0x421227]
emacs[0x421772]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x110e0)[0x7ff5a69270e0]
/root/.emacs.d/.local/straight/build-28.0.50/vterm/vterm-module.so(emacs_module_init+0x3a5)[0x7ff5905e44e5]
emacs[0x609089]
emacs[0x606824]
emacs[0x606d2a]
emacs[0x5e5258]
emacs(Ffuncall+0x323)[0x5d0583]
emacs[0x61edf2]
emacs[0x5d414f]
emacs[0x605c6e]
emacs[0x606891]
emacs[0x606d2a]
emacs[0x5d018d]
emacs[0x5d3da1]
emacs[0x5d493d]
emacs[0x5d419f]
emacs[0x5d441d]
emacs[0x5c0bf8]
emacs[0x5d419f]
emacs[0x5d552d]
emacs[0x5d419f]
emacs[0x5d441d]
emacs[0x5d419f]
emacs[0x5d493d]
emacs[0x5d419f]
emacs[0x5d576f]
emacs[0x5d419f]
emacs[0x5d552d]
emacs[0x5d419f]
emacs[0x5d45dd]
emacs(Ffuncall+0x187)[0x5d03e7]
emacs[0x5cc971]
emacs(Ffuncall+0x323)[0x5d0583]
emacs[0x5cd1c9]
emacs(Ffuncall+0x323)[0x5d0583]
emacs[0x61edf2]
emacs(Ffuncall+0x187)[0x5d03e7]
emacs[0x5d05da]
...
[1]    2895555 segmentation fault (core dumped)  emacs
```

**Comment by brotzeit** [comment] 2021-04-18 10:38
> bad news....crash again when compiling vterm, run emacs directly, no in daemon mode

Can't reproduce on arch.

**Comment by brotzeit** [comment] 2021-04-18 13:36
I've also tried it on ubuntu with the script and built libvterm successfully.

**Comment by DavidDeSimone** [comment] 2021-04-19 09:39
I'm also unable to reproduce this on Ubuntu. I may need some time to make a similar setup with Debian/gcc9 to try to reproduce.

**Comment by declantsien** [comment] 2023-03-01 11:18
I believe this is a duplicate of #148 . See [comment](https://github.com/emacs-ng/emacs-ng/issues/148#issuecomment-1449918275)

**Closed by declantsien** 2023-03-01 11:18 UTC
Labels: bug
